# Generated by Django 3.1.3 on 2020-12-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='create_date',
        ),
    ]
