# Generated by Django 3.1.3 on 2020-11-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('usertype', models.IntegerField(default=1)),
            ],
        ),
    ]
