# Generated by Django 3.1.3 on 2020-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='convertedPath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='facePath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='hairPath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='rid',
            field=models.IntegerField(unique=True),
        ),
    ]
