# Generated by Django 3.1.3 on 2020-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20201204_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='convertedPath',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='facePath',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='hairPath',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='rid',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
