# Generated by Django 3.1.3 on 2020-12-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20201204_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='idx',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
